spring:
      datasource:
   # useSSL=false  表示不使用加密通讯，本机的数据库没有必要加密
   # serverTimezone=CST 表示指定服务器的时区，CST=China Standard Time
        url: jdbc:mysql://127.0.0.1:3306/ruanjian2?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
        username: root
        password: root
      jpa:
#自动生产数据库的表，DDL表示数据定义语言，通常用来管理表结构的
        generate-ddl: true
#运行时自动生成的SQL语句打印出来
        show-sql: true
      redis:
        host: 47.112.13.17
        port: 6379
        database: 8
# 指定服务器在运行的时候，Tomcat使用的端口
# Spring Boot自带了一个阉割版Tomcat，默认不支持JSP，只是支持Servlet宿舍
server:
   port: 8080

